  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Pull and redeploy
        env:
          SHA: ${{ needs.build-and-push.outputs.sha_short }}
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          mkdir -p ~/app/deploy
          curl -o ~/app/deploy/docker-compose.yml https://raw.githubusercontent.com/innoetech-dev/my-full-stack-docker-app/refs/heads/feature/load-balancer/ci_docker-compose.yml
          cd ~/app/deploy
          sed -i "s|YOUR_DOCKERHUB_USERNAME|$DOCKER_USER|g" docker-compose.yml
          sed -i "s|YOUR_SHA|$SHA|g" docker-compose.yml
          docker compose pull
          docker compose up -d
